name: relu_plot_lib
description: 
  A simple graph tool for flutter desktop applications.
  Draw multiple graphs with thousands of data points without performance issues, 
  navigate around and scale the plot using your mouse, 
  annotate the plot with any widget you want and move it around the coordinate space of your data,
  attach crosshairs to your graphs to read and compare graph values.
version: 1.0.3
repository: https://github.com/optimazter/relu_plot_lib

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  test: ^1.24.9
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


