name: FlutterPlot Test

on:
    push:
      branches:
        - main
  
jobs:
    test:
        runs-on: macOS-latest

        steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            
        - run: |
            cd client
            flutter pub get
            flutter test

                    