name: FlutterPlot Test

on:
    push:
      branches:
        - main
  
jobs:
    test:
        runs-on: macOS-latest

        steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - name: Enter flutterplot package
          run: cd flutterplot  
        - run: flutter pub get
        - name: Run tests
          run: flutter test  --coverage

                    