name: tests

on:
    push:
      branches:
        - main
  
jobs:
    test:
        runs-on: macOS-latest

        steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            
        - name: Run Tests
          working-directory: ./flutterplot
          run: |
            flutter pub get
            flutter test

                    
